services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: nextpassword
      MYSQL_DATABASE: robots_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33306:3306"
    restart: always

  flask-app:
    build: .
    container_name: tms
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - "5055:5055"
    depends_on:
      - mysql
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./destination-manager
    ports:
      - "8089:80"
    depends_on:
      - flask-app
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  db_data: