from .update_coor_event import handle_update_coordinates
from .callrobot import handle_call_robot
from .update_status import handle_update_status
from .get_robot_statuses import handle_get_robot_statuses
from .heartbeatevent import handle_heartbeat